version: "3"

services:
  web:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .
    container_name: quiz_hero_reborn_web
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - postgres
    

  db:
    container_name: quiz_hero_reborn_db
    image: postgres
    ports:
      - "${DB_EXPOSE_PORT:-5432}:${DB_PORT:-5432}"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - postgres

  pgadmin:
    container_name: quiz_hero_reborn_pgadmin
    image: dpage/pgadmin4:7.1
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_EXPOSE_PORT:-5050}:${PGADMIN_PORT:-80}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
