name: Maven Package and Attach to Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Get JAR name
      id: get-jar
      run: echo "::set-output name=jar_name::$(basename $(find ./target -name '*.jar'))"

    - name: Attach JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/${{ steps.get-jar.outputs.jar_name }}
        asset_name: ${{ steps.get-jar.outputs.jar_name }}
        asset_content_type: application/java-archive
